export const meta = {
  name: "offline-t4-cuda-prep",
  description: "Offline workflow preparing telemetry parsing, synthetic vector generators, and paper drafting prior to GPU benchmarking.",
  phases: ["telemetry-and-data", "paper-drafting"]
};

phase("telemetry-and-data");

// Delegate simple tasks: Telemetry parser script and synthetic data generator script
const baselineTools = await parallel({
  telemetryParser: () => agent({
    id: "telemetry-parser-builder",
    provider: "mock", // simple delegation target (opencode / mock)
    prompt: `Write a clean standalone Python script 'research/src/parse_telemetry.py'.
It must ingest '/tmp/t4_telemetry.csv' generated by nvidia-smi.
The script should:
1. Parse columns: clocks.sm [MHz], power.draw [W], temperature.gpu [C], clocks_throttle_reasons.active.
2. Compute average and peak power draw, peak SM clock, and total duration.
3. Print a formatted summary report to stdout.
4. Save a summary JSON to 'research/telemetry_summary.json'.`
  }),

  syntheticDataGenerator: () => agent({
    id: "synthetic-data-builder",
    provider: "mock",
    prompt: `Write a Python script 'research/src/generate_synthetic_vectors.py'.
The script should:
1. Generate deterministic packed UINT32 weight matrices for M=1, 8, 32, 512, 4096 and K=N=4096.
2. Generate FP16 scale and zero-point vectors.
3. Save the tensors to 'research/scratch/synthetic_test_vectors.pt'.`
  })
});

phase("paper-drafting");

// Complex task: Systems paper drafting & LaTeX structural outline
const paperOutline = await agent({
  id: "systems-paper-author",
  provider: "codex", // complex reasoning task for main model
  prompt: `Draft a formal LaTeX systems paper outline for NeurIPS/ASPLOS targeting Tesla T4 CUDA optimizations.
Include sections for:
1. Introduction & 70W TDP Passive Cooling Challenge.
2. Signed INT4 LOP3 LUT 0x6A Bit-Manipulation & FP16 Exponent Injection.
3. Power-Aware 25% Occupancy Cap for 1590 MHz Clock Locking.
4. Fused Register-Level Backward GEMM + AdamW Optimizer.
Summarize all technical claims and mathematical proofs from findings.md.`
});

export default {
  baselineTools,
  paperOutline
};
